version: '3'

services:
  front:
    build: ./services/front
    hostname: front
    ports:
      - '3000:3000'

  nginx:
    build: ./services/nginx
    ports:
      - '80:80'
    depends_on:
      - front