version: '3'

services:

  minio:
    image: minio/minio:RELEASE.2023-02-22T18-23-45Z
    ports:
      - 9090:9090
      - 9091:9091
    volumes:
      - ./services/minio/data:/data
      - ./services/minio/export:/export
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    command: server /export --address :9090 --console-address :9091
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9090 minio minio123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/mybucket;
      /usr/bin/mc policy download myminio/mybucket;
      exit 0;
      "